### ISSUE TITLE
how to create a data source from Firebase firestore database?

### ISSUE THREAD

**Issue by FarzamAliKhan** [lianfanghua/flutter_editable_table#2]
Hi, I hope you could reach out to me asap as I have a project due very soon and I am stuck on using your table as I want an editable option. But I can't seem to understand when you use data as a source it also includes other customizations for the caption, number of columns, column names and styling and footer. WHILE the rows (which is what we want as a data source) is mixed together with these other customization. how can I create my own custom data source for those rows?

My Code: import 'dart:io';
import 'dart:typed_data';
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:dynamic_table/dynamic_table.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:path_provider/path_provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:pdf/widgets.dart' as pw;
import '../global/styles.dart';
import '../global/topBar.dart';
import '../utils/PermissionHelper.dart';
import 'LoginPage.dart';
import 'package:flutter_editable_table/constants.dart';
import 'package:flutter_editable_table/entities/table_entity.dart';
import 'package:flutter_editable_table/flutter_editable_table.dart';

class AttendanceScreen extends StatefulWidget {
  final String courseCode;
  final String sessionDocumentId;

  const AttendanceScreen({super.key, required this.courseCode, required this.sessionDocumentId});

  @override
  AttendanceScreenState createState() => AttendanceScreenState();
}

class AttendanceScreenState extends State<AttendanceScreen> {
  late Future<DocumentSnapshot<Map<String, dynamic>>>  attendanceData;

  final _editableTableKey = GlobalKey<EditableTableState>();
  late var data = {
    "column_count": null,
    "row_count": null,
    "addable": true,
    "removable": true,
    "caption": {
      "layout_direction": "row",
      "main_caption": {
        "title": "Attendance",
        "display": true,
        "editable": false,
        "style": {
          "font_weight": "bold",
          "font_size": 18.0,
          "font_color": "#333333",
          "background_color": null,
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        }
      },
    },
    "columns": [
  /*    {
        "primary_key": true,
        "title":"Roll Number",
        "name": "id",
        "type": "int",
        "format": null,
        "description": null,
        "display": false,
        "editable": false,
        "style": {
          "font_weight": "bold",
          "font_size": 14.0,
          "font_color": "#333333",
          "background_color": "#b5cfd2",
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        }
      },
      {
        "auto_increase": true,
        "type": "int",
        "format": "Step __VALUE__",
        "description": null,
        "display": true,
        "editable": false,
        "width_factor": 0.2,
        "style": {
          "font_weight": "bold",
          "font_size": 14.0,
          "font_color": "#333333",
          "background_color": "#b5cfd2",
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        }
      },*/
      {
        "name": "roll_number",
        "title": "Roll Number",
        "type": "integer",
        "format": null,
        "description": "User Name",
        "display": true,
        "editable": true,
        "width_factor": 0.25,
        "input_decoration": {
          "min_lines": 1,
          "max_lines": 1,
          "max_length": 128,
          "hint_text": "Please input the name"
        },
        "constrains": {"required": true},
        "style": {
          "font_weight": "bold",
          "font_size": 14.0,
          "font_color": "#333333",
          "background_color": "#b5cfd2",
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        },
      },
      {
        "name": "name",
        "title": "Name",
        "type": "string",
        "format": null,
        "description": "Age",
        "display": true,
        "editable": true,
        "width_factor": 0.5,
        "input_decoration": {
          "min_lines": 1,
          "max_lines": 1,
          "max_length": 3,
          "hint_text": "Please input the age"
        },
        "constrains": {"required": true, "minimum": 1, "maximum": 120},
        "style": {
          "font_weight": "bold",
          "font_size": 14.0,
          "font_color": "#333333",
          "background_color": "#b5cfd2",
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        }
      },
      {
        "name": "status",
        "title": "Status",
        "type": "string",
        "format": null,
        "description": "Salary",
        "display": true,
        "editable": true,
        "width_factor": 0.25,
        "input_decoration": {
          "min_lines": 1,
          "max_lines": 1,
          "max_length": 128,
          "hint_text": "Please input the salary"
        },
        "constrains": {"required": true, "minimum": -100, "maximum": 10000},
        "style": {
          "font_weight": "bold",
          "font_size": 14.0,
          "font_color": "#333333",
          "background_color": "#b5cfd2",
          "horizontal_alignment": "center",
          "vertical_alignment": "center",
          "text_align": "center"
        }
      },
    ],
    "rows": [
        {"name": "Farzam - 86"},
        {"name": "Faiq - 96"},
        {"name": "Talha - 88"},
    ],
    "footer": {
      "layout_direction": "row",
      "content": [
        {
          "title": "Total Present: 22",
          "display": true,
          "editable": false,
          "style": {
            "font_weight": "normal",
            "font_size": 14.0,
            "font_color": "#333333",
            "background_color": null,
            "horizontal_alignment": "center",
            "vertical_alignment": "center",
            "text_align": "center"
          }
        },
        {
          "title": "Total Absent: 22",
          "display": true,
          "editable": false,
          "style": {
            "font_weight": "normal",
            "font_size": 14.0,
            "font_color": "#333333",
            "background_color": null,
            "horizontal_alignment": "center",
            "vertical_alignment": "center",
            "text_align": "center"
          }
        },
      ]
    }
  };

  bool editing = false;

  @override
  void initState() {
    attendanceData = getAttendanceData();
    super.initState();
  }

   Future<DocumentSnapshot<Map<String, dynamic>>> getAttendanceData() async {
    return FirebaseFirestore.instance
            .collection('attendance')
            .doc(widget.courseCode)
            .collection('session')
            .doc(widget.sessionDocumentId)
            .get();
  }
 // Function to map Firebase data to table rows
          List<Map<String, dynamic>> mapFirebaseDataToTableRows(Map<String, dynamic> attendanceData) {
              List<Map<String, dynamic>> rows = [];

              // Extract the required fields from the attendanceData
              List<String> presentStudents = List<String>.from(attendanceData['presentStudents'] ?? []);

              // Map presen tStudents data to table rows
              for (String student in presentStudents) {
                rows.add({
                  "name": student,  // Assuming "name" is the key in your table data
                  // Add other relevant fields here
                });
              }

            return rows;
          }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text(
            "TEACHER",
            style: GoogleFonts.ubuntu(
                color: Colors.white, fontWeight: FontWeight.bold),
          ),
          automaticallyImplyLeading: false,
          backgroundColor: AppColors.secondaryColor,
          centerTitle: true,
          shadowColor: Colors.blueGrey,
          leading: const Icon(
            Icons.person,
            color: Colors.white,
          ),
          actions: [
            IconButton(
              icon: const Icon(
                Icons.logout_outlined,
                color: Colors.white,
              ),
              onPressed: () {
                FirebaseAuth.instance.signOut().then((value) {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => const LoginPage()));
                }).onError((error, stackTrace) {
                  print("Error");
                });
              },
            ),
            GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () {
              WidgetsBinding.instance.focusManager.primaryFocus?.unfocus();
              _editableTableKey.currentState?.addRow();
            },
            child: const Icon(Icons.add),
          ),
          const SizedBox(width: 8.0),
          GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () {
              WidgetsBinding.instance.focusManager.primaryFocus?.unfocus();
              _editableTableKey.currentState?.readOnly = editing;
              setState(() {
                editing = !editing;
              });
              if (!editing) {
                print(
                    'table filling status: ${_editableTableKey.currentState?.currentData.isFilled}');
              }
            },
            child: Icon(!editing ? Icons.edit : Icons.check),
          ),
          const SizedBox(width: 14.0),
          ]
      ),
      floatingActionButton: FloatingActionButton(
        tooltip: 'Print Document',
        onPressed: () async {
          // Wait for the attendanceData Future to complete
          DocumentSnapshot<Map<String, dynamic>> snapshot = await attendanceData;
          print(snapshot);
          print('attendance: $attendanceData.size');
          final courseCode = widget.courseCode;
          // Check if the snapshot contains data
          if (snapshot.exists) {
            Uint8List pdfBytes = await buildPdf(snapshot, courseCode);
            await savePdf(pdfBytes);
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('No data found'),
              duration: Duration(seconds: 5) ,
              )
            );
          }
        },
        child: const Icon(Icons.print),
      ),
      body: FutureBuilder<DocumentSnapshot<Map<String, dynamic>>>(
        future: attendanceData,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const CircularProgressIndicator(); // Loading indicator while data is being fetched
          }
          if (!snapshot.hasData || !snapshot.data!.exists) {

            return const Text('No data found'); // Handle the case where the document doesn't exist
          }
          // Access the attendance data from the snapshot
            final attendanceData = snapshot.data!.data()!;
            print('attendanceData: $attendanceData');

          // Extract the required fields from the attendanceData
          List<String> absentStudents = List<String>.from(attendanceData['absentStudents'] ?? []);
          List<String> presentStudents = List<String>.from(attendanceData['presentStudents'] ?? []);
          print(presentStudents[0]);
          // Print the individual names

          // Map Firebase data to table rows
          List<Map<String, dynamic>> tableRows = mapFirebaseDataToTableRows(attendanceData);
          print('tableRows: $tableRows');

          // Convert the tableRows list to the expected format
            List<Map<String, dynamic>> formattedRows = tableRows.map((row) {
              return {"name": row["name"]};
            }).toList();

            print('formattedRows: $formattedRows');

            // Update the data variable with the populated rows
            Map<String, Object?> updatedData = {
              "rows": formattedRows,
            };
            print('uupdatedData: $updatedData');
            print(data);

          String section = attendanceData['section'] ?? '';
          DateTime date = attendanceData['date'].toDate();

          return SingleChildScrollView(
            child: EditableTable(captionTextStyle: const TextStyle(color: Colors.black),
              key: _editableTableKey,
              data: data,
              entity: TableEntity.fromJson(data),
              readOnly: true,
              tablePadding: EdgeInsets.all(8.0),
              captionBorder: const Border(
                top: BorderSide(color: Color(0xFF999999)),
                left: BorderSide(color: Color(0xFF999999)),
                right: BorderSide(color: Color(0xFF999999)),
              ),
              headerBorder: Border.all(color: Color(0xFF999999)),
              rowBorder: Border.all(color: Color(0xFF999999)),
              footerBorder: Border.all(color: Color(0xFF999999)),
              removeRowIcon: const Icon(
                Icons.remove_circle_outline,
                size: 24.0,
                color: Colors.redAccent,
              ),
              addRowIcon: const Icon(
                Icons.add_circle_outline,
                size: 24.0,
                color: Colors.white,
              ),
              addRowIconContainerBackgroundColor: Colors.blueAccent,
              formFieldAutoValidateMode: AutovalidateMode.always,
              onRowRemoved: (row) {
                print('row removed: ${row.toString()}');
              },
              onRowAdded: () {
                print('row added');
              },
              onFilling: (FillingArea area, dynamic value) {
                print('filling: ${area.toString()}, value: ${value.toString()}');
              },
              onSubmitted: (FillingArea area, dynamic value) {
                print('submitted: ${area.toString()}, value: ${value.toString()}');
              },
            ),
          );
        },
      ),
    );
  }

**Comment by FarzamAliKhan** [comment]
> Hi, I hope you could reach out to me asap as I have a project due very soon and I am stuck on using your table as I want an editable option. But I can't seem to understand when you use data as a source it also includes other customizations for the caption, number of columns, column names and styling and footer. WHILE the rows (which is what we want as a data source) is mixed together with these other customization. how can I create my own custom data source for those rows?
> 
> My Code: import 'dart:io'; import 'dart:typed_data'; import 'package:awesome_notifications/awesome_notifications.dart'; import 'package:dynamic_table/dynamic_table.dart'; import 'package:firebase_auth/firebase_auth.dart'; import 'package:flutter/material.dart'; import 'package:flutter/services.dart'; import 'package:google_fonts/google_fonts.dart'; import 'package:path_provider/path_provider.dart'; import 'package:cloud_firestore/cloud_firestore.dart'; import 'package:pdf/widgets.dart' as pw; import '../global/styles.dart'; import '../global/topBar.dart'; import '../utils/PermissionHelper.dart'; import 'LoginPage.dart'; import 'package:flutter_editable_table/constants.dart'; import 'package:flutter_editable_table/entities/table_entity.dart'; import 'package:flutter_editable_table/flutter_editable_table.dart';
> 
> class AttendanceScreen extends StatefulWidget { final String courseCode; final String sessionDocumentId;
> 
> const AttendanceScreen({super.key, required this.courseCode, required this.sessionDocumentId});
> 
> @OverRide AttendanceScreenState createState() => AttendanceScreenState(); }
> 
> class AttendanceScreenState extends State { late Future<DocumentSnapshot<Map<String, dynamic>>> attendanceData;
> 
> final _editableTableKey = GlobalKey(); late var data = { "column_count": null, "row_count": null, "addable": true, "removable": true, "caption": { "layout_direction": "row", "main_caption": { "title": "Attendance", "display": true, "editable": false, "style": { "font_weight": "bold", "font_size": 18.0, "font_color": "#333333", "background_color": null, "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, }, "columns": [ /* { "primary_key": true, "title":"Roll Number", "name": "id", "type": "int", "format": null, "description": null, "display": false, "editable": false, "style": { "font_weight": "bold", "font_size": 14.0, "font_color": "#333333", "background_color": "#b5cfd2", "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, { "auto_increase": true, "type": "int", "format": "Step **VALUE**", "description": null, "display": true, "editable": false, "width_factor": 0.2, "style": { "font_weight": "bold", "font_size": 14.0, "font_color": "#333333", "background_color": "#b5cfd2", "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } },*/ { "name": "roll_number", "title": "Roll Number", "type": "integer", "format": null, "description": "User Name", "display": true, "editable": true, "width_factor": 0.25, "input_decoration": { "min_lines": 1, "max_lines": 1, "max_length": 128, "hint_text": "Please input the name" }, "constrains": {"required": true}, "style": { "font_weight": "bold", "font_size": 14.0, "font_color": "#333333", "background_color": "#b5cfd2", "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" }, }, { "name": "name", "title": "Name", "type": "string", "format": null, "description": "Age", "display": true, "editable": true, "width_factor": 0.5, "input_decoration": { "min_lines": 1, "max_lines": 1, "max_length": 3, "hint_text": "Please input the age" }, "constrains": {"required": true, "minimum": 1, "maximum": 120}, "style": { "font_weight": "bold", "font_size": 14.0, "font_color": "#333333", "background_color": "#b5cfd2", "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, { "name": "status", "title": "Status", "type": "string", "format": null, "description": "Salary", "display": true, "editable": true, "width_factor": 0.25, "input_decoration": { "min_lines": 1, "max_lines": 1, "max_length": 128, "hint_text": "Please input the salary" }, "constrains": {"required": true, "minimum": -100, "maximum": 10000}, "style": { "font_weight": "bold", "font_size": 14.0, "font_color": "#333333", "background_color": "#b5cfd2", "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, ], "rows": [ {"name": "Farzam - 86"}, {"name": "Faiq - 96"}, {"name": "Talha - 88"}, ], "footer": { "layout_direction": "row", "content": [ { "title": "Total Present: 22", "display": true, "editable": false, "style": { "font_weight": "normal", "font_size": 14.0, "font_color": "#333333", "background_color": null, "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, { "title": "Total Absent: 22", "display": true, "editable": false, "style": { "font_weight": "normal", "font_size": 14.0, "font_color": "#333333", "background_color": null, "horizontal_alignment": "center", "vertical_alignment": "center", "text_align": "center" } }, ] } };
> 
> bool editing = false;
> 
> @OverRide void initState() { attendanceData = getAttendanceData(); super.initState(); }
> 
> Future<DocumentSnapshot<Map<String, dynamic>>> getAttendanceData() async { return FirebaseFirestore.instance .collection('attendance') .doc(widget.courseCode) .collection('session') .doc(widget.sessionDocumentId) .get(); } // Function to map Firebase data to table rows List<Map<String, dynamic>> mapFirebaseDataToTableRows(Map<String, dynamic> attendanceData) { List<Map<String, dynamic>> rows = [];
> 
> ```
>           // Extract the required fields from the attendanceData
>           List<String> presentStudents = List<String>.from(attendanceData['presentStudents'] ?? []);
> 
>           // Map presen tStudents data to table rows
>           for (String student in presentStudents) {
>             rows.add({
>               "name": student,  // Assuming "name" is the key in your table data
>               // Add other relevant fields here
>             });
>           }
> 
>         return rows;
>       }
> ```
> 
> @OverRide Widget build(BuildContext context) { return Scaffold( appBar: AppBar( title: Text( "TEACHER", style: GoogleFonts.ubuntu( color: Colors.white, fontWeight: FontWeight.bold), ), automaticallyImplyLeading: false, backgroundColor: AppColors.secondaryColor, centerTitle: true, shadowColor: Colors.blueGrey, leading: const Icon( Icons.person, color: Colors.white, ), actions: [ IconButton( icon: const Icon( Icons.logout_outlined, color: Colors.white, ), onPressed: () { FirebaseAuth.instance.signOut().then((value) { Navigator.push( context, MaterialPageRoute( builder: (context) => const LoginPage())); }).onError((error, stackTrace) { print("Error"); }); }, ), GestureDetector( behavior: HitTestBehavior.opaque, onTap: () { WidgetsBinding.instance.focusManager.primaryFocus?.unfocus(); _editableTableKey.currentState?.addRow(); }, child: const Icon(Icons.add), ), const SizedBox(width: 8.0), GestureDetector( behavior: HitTestBehavior.opaque, onTap: () { WidgetsBinding.instance.focusManager.primaryFocus?.unfocus(); _editableTableKey.currentState?.readOnly = editing; setState(() { editing = !editing; }); if (!editing) { print( 'table filling status: ${_editableTableKey.currentState?.currentData.isFilled}'); } }, child: Icon(!editing ? Icons.edit : Icons.check), ), const SizedBox(width: 14.0), ] ), floatingActionButton: FloatingActionButton( tooltip: 'Print Document', onPressed: () async { // Wait for the attendanceData Future to complete DocumentSnapshot<Map<String, dynamic>> snapshot = await attendanceData; print(snapshot); print('attendance: $attendanceData.size'); final courseCode = widget.courseCode; // Check if the snapshot contains data if (snapshot.exists) { Uint8List pdfBytes = await buildPdf(snapshot, courseCode); await savePdf(pdfBytes); } else { ScaffoldMessenger.of(context).showSnackBar( const SnackBar( content: Text('No data found'), duration: Duration(seconds: 5) , ) ); } }, child: const Icon(Icons.print), ), body: FutureBuilder<DocumentSnapshot<Map<String, dynamic>>>( future: attendanceData, builder: (context, snapshot) { if (snapshot.connectionState == ConnectionState.waiting) { return const CircularProgressIndicator(); // Loading indicator while data is being fetched } if (!snapshot.hasData || !snapshot.data!.exists) {
> 
> ```
>         return const Text('No data found'); // Handle the case where the document doesn't exist
>       }
>       // Access the attendance data from the snapshot
>         final attendanceData = snapshot.data!.data()!;
>         print('attendanceData: $attendanceData');
> 
>       // Extract the required fields from the attendanceData
>       List<String> absentStudents = List<String>.from(attendanceData['absentStudents'] ?? []);
>       List<String> presentStudents = List<String>.from(attendanceData['presentStudents'] ?? []);
>       print(presentStudents[0]);
>       // Print the individual names
> 
>       // Map Firebase data to table rows
>       List<Map<String, dynamic>> tableRows = mapFirebaseDataToTableRows(attendanceData);
>       print('tableRows: $tableRows');
> 
>       // Convert the tableRows list to the expected format
>         List<Map<String, dynamic>> formattedRows = tableRows.map((row) {
>           return {"name": row["name"]};
>         }).toList();
> 
>         print('formattedRows: $formattedRows');
> 
>         // Update the data variable with the populated rows
>         Map<String, Object?> updatedData = {
>           "rows": formattedRows,
>         };
>         print('uupdatedData: $updatedData');
>         print(data);
> 
>       String section = attendanceData['section'] ?? '';
>       DateTime date = attendanceData['date'].toDate();
> 
>       return SingleChildScrollView(
>         child: EditableTable(captionTextStyle: const TextStyle(color: Colors.black),
>           key: _editableTableKey,
>           data: data,
>           entity: TableEntity.fromJson(data),
>           readOnly: true,
>           tablePadding: EdgeInsets.all(8.0),
>           captionBorder: const Border(
>             top: BorderSide(color: Color(0xFF999999)),
>             left: BorderSide(color: Color(0xFF999999)),
>             right: BorderSide(color: Color(0xFF999999)),
>           ),
>           headerBorder: Border.all(color: Color(0xFF999999)),
>           rowBorder: Border.all(color: Color(0xFF999999)),
>           footerBorder: Border.all(color: Color(0xFF999999)),
>           removeRowIcon: const Icon(
>             Icons.remove_circle_outline,
>             size: 24.0,
>             color: Colors.redAccent,
>           ),
>           addRowIcon: const Icon(
>             Icons.add_circle_outline,
>             size: 24.0,
>             color: Colors.white,
>           ),
>           addRowIconContainerBackgroundColor: Colors.blueAccent,
>           formFieldAutoValidateMode: AutovalidateMode.always,
>           onRowRemoved: (row) {
>             print('row removed: ${row.toString()}');
>           },
>           onRowAdded: () {
>             print('row added');
>           },
>           onFilling: (FillingArea area, dynamic value) {
>             print('filling: ${area.toString()}, value: ${value.toString()}');
>           },
>           onSubmitted: (FillingArea area, dynamic value) {
>             print('submitted: ${area.toString()}, value: ${value.toString()}');
>           },
>         ),
>       );
>     },
>   ),
> );
> ```
> 
> }

and How can I pass my own custom data to EditableTable() widget?

**Comment by lianfanghua** [comment]
Hi, @FarzamAliKhan, flutter_editable_table is a front-end data display and editing component. When I designed it, I did not consider it to directly connect and manage data sources.

I designed two data source parameters for it, which are Json and entities used internally in the component(see lib/entities/table_entity.dart). Please see the documentation here: https://github.com/lianfanghua/flutter_editable_table?tab=readme-ov-file#data-source
```dart
// If both `data` and `entity` are provided, `entity` will be used first
EditableTable(
   // Use `Map<String, dynamic>` as data source
   data: data,
   // Use `TableEntity` as data source
   entity: TableEntity.fromJson(data),
   ...
)
```
I don't know the structure of your database and tables, so I can't tell you how to structure your own data, but I can tell you my approach to designing this component:

We all know that tables are composed of main titles, subtitles, columns, and rows (may also include paging), so in order for the component to display normally and to know which unit the user has changed when editing, I must tell the component, Title, subtitle content, font size and other formats. And the format of each column (text, number, time or other), and the value of each row.

Therefore, the requirements for data format are also the same, and you can construct your own data according to this.

**Comment by FarzamAliKhan** [comment]
> Hi, @FarzamAliKhan, flutter_editable_table is a front-end data display and editing component. When I designed it, I did not consider it to directly connect and manage data sources.
> 
> I designed two data source parameters for it, which are Json and entities used internally in the component(see lib/entities/table_entity.dart). Please see the documentation here: https://github.com/lianfanghua/flutter_editable_table?tab=readme-ov-file#data-source
> 
> ```dart
> // If both `data` and `entity` are provided, `entity` will be used first
> EditableTable(
>    // Use `Map<String, dynamic>` as data source
>    data: data,
>    // Use `TableEntity` as data source
>    entity: TableEntity.fromJson(data),
>    ...
> )
> ```
> 
> I don't know the structure of your database and tables, so I can't tell you how to structure your own data, but I can tell you my approach to designing this component:
> 
> We all know that tables are composed of main titles, subtitles, columns, and rows (may also include paging), so in order for the component to display normally and to know which unit the user has changed when editing, I must tell the component, Title, subtitle content, font size and other formats. And the format of each column (text, number, time or other), and the value of each row.
> 
> Therefore, the requirements for data format are also the same, and you can construct your own data according to this.

Thank you for the quick reply, Well thats the thing I can not figure out how to construct my own data with your format Columns, captions, footer etc each time I pass data on EditableData. Because only rows change in my case, rest of the designing is the same throughout. I can't seem to concatenate rows with your data format as well.

**Comment by lianfanghua** [comment]
I'm very sorry, I didn't consider the scenario where the data format remains unchanged but the data changes individually.

You can try the following options:
1. First obtain the title, column format, etc. of the table, use TableEntity.fromJson to construct an entity (there is no row data at this time), and do not bind it to the component for the time being;
2. Get the row data and insert it into TableEntity.rows built in step 1;
3. Bind to the component;

If you need to update the data, you can copy it through TableEntity.copy, then clear the rows, reinsert the new data, and finally bind it to the component.
